defaults:
  minimum_number_of_regions: 8
  maximum_number_of_regions: 12 

  minimum_tiles_per_mountains_region: 4
  maximum_tiles_per_mountains_region: 8

  minimum_tiles_per_plains_region: 4
  maximum_tiles_per_plains_region: 8

  minimum_tiles_per_forest_region: 4
  maximum_tiles_per_forest_region: 8

  minimum_tiles_per_desert_region: 4
  maximum_tiles_per_desert_region: 8

  minimum_tiles_per_coast_region: 4
  maximum_tiles_per_coast_region: 8

  minimum_number_of_dungeons: 9
  maximum_number_of_dungeons: 13

  minimum_number_of_settlements: 6
  maximum_number_of_settlements: 9

  region_classes: !weighted
    - MountainsRegion
    - PlainsRegion
    - ForestRegion
    - DesertRegion
    - CoastRegion

  settlement_classes: !weighted
    - Village^3
    - Town^3
    - City^2
    # - Hut
    
  dungeon_classes: !weighted
    - Cavern
    - Temple
    - Tomb
    # - Mine
    # - Ruins
